# Generated by Django 2.2.6 on 2019-10-21 09:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blood_bank_details',
            fields=[
                ('name', models.CharField(max_length=264, primary_key=True, serialize=False, unique=True)),
                ('address', models.CharField(max_length=512)),
                ('phone_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='camp_schedule',
            fields=[
                ('code', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=264)),
                ('address', models.CharField(max_length=512)),
                ('contact_person', models.CharField(max_length=264)),
                ('phone_no', models.CharField(max_length=20)),
                ('schedule_date', models.DateField()),
                ('no_of_beds', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='donor',
            fields=[
                ('donor_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=264)),
                ('address', models.CharField(max_length=512)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('marital_status', models.CharField(blank=True, max_length=30)),
                ('phone_no', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=4)),
                ('occupation', models.CharField(blank=True, max_length=30)),
                ('email_id', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='employee_details',
            fields=[
                ('employee_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=264)),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('qualification', models.CharField(max_length=264)),
                ('designation', models.CharField(max_length=264)),
                ('address', models.CharField(max_length=512)),
                ('phone_no', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=4)),
                ('email_id', models.EmailField(max_length=254)),
                ('joining_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='equipment_details',
            fields=[
                ('equipment_code', models.IntegerField(primary_key=True, serialize=False)),
                ('equipment_name', models.CharField(max_length=264)),
                ('no_of_equipment', models.IntegerField()),
                ('purchase_date', models.DateField()),
                ('purchased_from', models.CharField(max_length=264)),
                ('cost_per_piece', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='stock_details',
            fields=[
                ('blood_group', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('no_of_bags', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('recipient_name', models.CharField(max_length=264)),
                ('date', models.DateField()),
                ('blood_group', models.CharField(max_length=4)),
                ('no_of_bags', models.IntegerField()),
                ('bill_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user_login',
            fields=[
                ('username', models.CharField(max_length=264, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='donor_health',
            fields=[
                ('donor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bb_app.donor')),
                ('body_weight', models.PositiveIntegerField()),
                ('temprature', models.PositiveIntegerField()),
                ('pulse', models.PositiveIntegerField()),
                ('blood_pressure', models.PositiveIntegerField()),
                ('haemoglobin', models.PositiveIntegerField()),
                ('test_vdrl', models.CharField(max_length=4)),
                ('test_hbsag', models.CharField(max_length=4)),
                ('test_mp', models.CharField(max_length=4)),
                ('test_hcv', models.CharField(max_length=4)),
                ('test_hiv', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='blood_bag',
            fields=[
                ('blood_bag_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('status', models.BooleanField()),
                ('collection_date', models.DateField(verbose_name=datetime.date(2019, 10, 21))),
                ('expiry_date', models.DateField()),
                ('entered_by', models.CharField(max_length=264)),
                ('bag_weight', models.IntegerField()),
                ('blood_bank_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bb_app.blood_bank_details')),
                ('donor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bb_app.donor')),
            ],
        ),
    ]
